[project]
name = "cuda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "jupytext>=1.16.6",
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
]

[tool.jupytext]
formats = "ipynb,py:percent"
